plan:
  replace_mode: NONE
  backup_dir: "/var/tmp/deployer-work/backup"
  temp_dir: "/var/tmp/deployer-work/tmp"
  include_extensions: []
  exclude_extensions: []

source:
  archive_url: "http://localhost:5000/extensions.zip"
  manifest_url: "http://localhost:5000/manifest.json"
  retries: 1

deployment:
  target_dir: "~/.vscode/extensions"
  verify_integrity: ERROR
  dry_run: false

logging:
  level: INFO
  file: "/var/tmp/deployer-work/deployer.log"
  to_console: true
  to_syslog: false


#Just to test locally without touching the yamls already in here